-- SCHEMAS AND EXTENSION

-- SCHEMA: sa
DROP SCHEMA IF EXISTS sa CASCADE;
CREATE SCHEMA IF NOT EXISTS sa
    AUTHORIZATION postgres;
	
-- SCHEMA: pa
DROP SCHEMA IF EXISTS pa CASCADE;
CREATE SCHEMA IF NOT EXISTS pa
    AUTHORIZATION postgres;

-- PostGIS Extension
CREATE EXTENSION IF NOT EXISTS postgis;